In [1]:
# !pip install gensim scikit-learn pandas numpy torch tqdm

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import classification_report, confusion_matrix
from collections import Counter
import gensim

# --- UČITAVANJE PODATAKA ---
train_df = pd.read_csv('train-2.csv')
test2_df = pd.read_csv('test-2.csv')

def get_text_column(df):
    for col in df.columns:
        if col.lower() in ['sentence', 'text']:
            return col
    raise ValueError("Nema stupca 'Sentence' ili 'Text'!")

train_text_col = get_text_column(train_df)
test2_text_col = get_text_column(test2_df)

# --- TOKENIZACIJA I VOKABULAR ---
def tokenize(text):
    return text.lower().split()

counter = Counter()
for text in train_df[train_text_col]:
    counter.update(tokenize(text))
vocab = {word: idx+2 for idx, (word, _) in enumerate(counter.most_common())}
vocab['<unk>'] = 0
vocab['<pad>'] = 1

# --- EMBEDDING ---
embedding_path = 'cc.hr.300.vec'
embeddings = gensim.models.KeyedVectors.load_word2vec_format(embedding_path)
embedding_dim = embeddings.vector_size
embedding_matrix = np.zeros((len(vocab), embedding_dim))
for word, idx in vocab.items():
    if word in embeddings:
        embedding_matrix[idx] = embeddings[word]
    else:
        embedding_matrix[idx] = np.random.normal(scale=0.6, size=(embedding_dim, ))

# --- DATASET ---
class TextDataset(Dataset):
    def __init__(self, df, text_col, vocab, max_len=50):
        self.texts = df[text_col].tolist()
        self.labels = df['Label'].tolist()
        self.vocab = vocab
        self.max_len = max_len
    def __len__(self):
        return len(self.texts)
    def __getitem__(self, idx):
        tokens = tokenize(self.texts[idx])
        ids = [self.vocab.get(token, self.vocab['<unk>']) for token in tokens][:self.max_len]
        ids += [self.vocab['<pad>']] * (self.max_len - len(ids))
        return torch.tensor(ids), torch.tensor(self.labels[idx])

max_len = 50
batch_size = 32
train_ds = TextDataset(train_df, train_text_col, vocab, max_len)
test2_ds = TextDataset(test2_df, test2_text_col, vocab, max_len)

train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
test2_dl = DataLoader(test2_ds, batch_size=batch_size)

# --- MODELI ---
class LSTMClassifier(nn.Module):
    def __init__(self, embedding_matrix, hidden_dim=256, num_classes=3, dropout=0.8):
        super().__init__()
        num_embeddings, embedding_dim = embedding_matrix.shape
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
        self.embedding.weight.data.copy_(torch.from_numpy(embedding_matrix))
        self.embedding.weight.requires_grad = False
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim, num_classes)
    def forward(self, x):
        x = self.embedding(x)
        _, (hidden, _) = self.lstm(x)
        out = self.dropout(hidden[-1])
        return self.fc(out)

class GRUClassifier(nn.Module):
    def __init__(self, embedding_matrix, hidden_dim=256, num_classes=3, dropout=0.8):
        super().__init__()
        num_embeddings, embedding_dim = embedding_matrix.shape
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
        self.embedding.weight.data.copy_(torch.from_numpy(embedding_matrix))
        self.embedding.weight.requires_grad = False
        self.gru = nn.GRU(embedding_dim, hidden_dim, batch_first=True)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim, num_classes)
    def forward(self, x):
        x = self.embedding(x)
        _, hidden = self.gru(x)
        out = self.dropout(hidden[-1])
        return self.fc(out)

class CNNClassifier(nn.Module):
    def __init__(self, embedding_matrix, num_filters=128, kernel_sizes=[3,4,5], num_classes=3, dropout=0.8):
        super().__init__()
        num_embeddings, embedding_dim = embedding_matrix.shape
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
        self.embedding.weight.data.copy_(torch.from_numpy(embedding_matrix))
        self.embedding.weight.requires_grad = False
        self.convs = nn.ModuleList([
            nn.Conv2d(1, num_filters, (k, embedding_dim)) for k in kernel_sizes
        ])
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(num_filters * len(kernel_sizes), num_classes)
    def forward(self, x):
        x = self.embedding(x)
        x = x.unsqueeze(1)
        x = [torch.relu(conv(x)).squeeze(3) for conv in self.convs]
        x = [torch.max(pool, dim=2)[0] for pool in x]
        x = torch.cat(x, dim=1)
        x = self.dropout(x)
        return self.fc(x)

# --- TRENING I EVAL ---
def train_epoch(model, dataloader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    for x, y in dataloader:
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()
        logits = model(x)
        loss = criterion(logits, y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(dataloader)

def eval_model(model, dataloader, device):
    model.eval()
    preds, targets = [], []
    with torch.no_grad():
        for x, y in dataloader:
            x = x.to(device)
            logits = model(x)
            pred = logits.argmax(1).cpu().numpy()
            preds.extend(pred)
            targets.extend(y.numpy())
    return np.array(preds), np.array(targets)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def run_training(model_class, name, epochs=50, dropout=0.8, lr=5e-4):
    print(f"\n{name} training...")
    model = model_class(embedding_matrix, dropout=dropout).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    for epoch in range(epochs):
        train_loss = train_epoch(model, train_dl, optimizer, criterion, device)
        if (epoch+1) % 5 == 0 or epoch == 0:
            print(f"{name} Epoch {epoch+1}: Train loss {train_loss:.4f}")
    preds, targets = eval_model(model, test2_dl, device)
    report = classification_report(targets, preds, digits=4, output_dict=True, target_names=["positive", "neutral", "negative"])
    matrix = confusion_matrix(targets, preds)
    print(f"\n{name} Classification report:\n", classification_report(targets, preds, digits=4, target_names=["positive", "neutral", "negative"]))
    print(f"{name} Confusion matrix:\n", matrix)
    return {
        'precision': report['macro avg']['precision'],
        'recall': report['macro avg']['recall'],
        'f1': report['macro avg']['f1-score'],
        'accuracy': report['accuracy'],
        'confusion_matrix': matrix.tolist(),
        'full_report': classification_report(targets, preds, digits=4, target_names=["positive", "neutral", "negative"])
    }

lstm_results = run_training(LSTMClassifier, "LSTM", epochs=50, dropout=0.8, lr=5e-4)
gru_results = run_training(GRUClassifier, "GRU", epochs=50, dropout=0.8, lr=5e-4)
cnn_results = run_training(CNNClassifier, "CNN", epochs=50, dropout=0.8, lr=5e-4)

# --- Spremi u results.md ---
with open('results.md', 'w', encoding='utf-8') as f:
    for model_name, results in [('LSTM', lstm_results), ('GRU', gru_results), ('CNN', cnn_results)]:
        f.write(f"## {model_name}\n\n")
        f.write(f"- Precision: {results['precision']:.4f}\n")
        f.write(f"- Recall: {results['recall']:.4f}\n")
        f.write(f"- F1: {results['f1']:.4f}\n")
        f.write(f"- Accuracy: {results['accuracy']:.4f}\n")
        f.write(f"- Confusion matrix: {results['confusion_matrix']}\n\n")
        f.write(f"Full classification report:\n{results['full_report']}\n\n")
print("Rezultati za grupu 2 spremljeni su u results.md")



LSTM training...
LSTM Epoch 1: Train loss 0.9620
LSTM Epoch 5: Train loss 0.9446
LSTM Epoch 10: Train loss 0.9351
LSTM Epoch 15: Train loss 0.9281
LSTM Epoch 20: Train loss 0.9077
LSTM Epoch 25: Train loss 0.8995
LSTM Epoch 30: Train loss 0.8916
LSTM Epoch 35: Train loss 0.8837
LSTM Epoch 40: Train loss 0.8802
LSTM Epoch 45: Train loss 0.8276
LSTM Epoch 50: Train loss 0.5568

LSTM Classification report:
               precision    recall  f1-score   support

    positive     0.3684    0.0648    0.1102       216
     neutral     0.5899    0.9513    0.7282       431
    negative     0.1250    0.0106    0.0196        94

    accuracy                         0.5735       741
   macro avg     0.3611    0.3422    0.2860       741
weighted avg     0.4664    0.5735    0.4582       741

LSTM Confusion matrix:
 [[ 14 200   2]
 [ 16 410   5]
 [  8  85   1]]

GRU training...
GRU Epoch 1: Train loss 1.0010
GRU Epoch 5: Train loss 0.9708
GRU Epoch 10: Train loss 0.9342
GRU Epoch 15: Train loss 0.86