In [1]:
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
from sklearn.metrics import classification_report, confusion_matrix

def load_and_prepare_data(train_path):
    df = pd.read_csv(train_path)
    df = df.rename(columns={"Label": "label"})
    return Dataset.from_pandas(df)

def load_and_prepare_test_data(test_path):
    df = pd.read_csv(test_path)
    df = df.rename(columns={"Label": "label"})
    return Dataset.from_pandas(df), df

def tokenize_dataset(dataset, tokenizer):
    def tokenize_function(examples):
        return tokenizer(examples['Sentence'], padding='max_length', truncation=True, max_length=128)
    tokenized = dataset.map(tokenize_function, batched=True)
    tokenized.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
    return tokenized

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = torch.argmax(torch.tensor(logits), axis=1).numpy()
    report = classification_report(labels, preds, output_dict=True)
    acc = report['accuracy']
    f1 = report['macro avg']['f1-score']
    return {'accuracy': acc, 'f1_macro': f1}

def train_and_evaluate(model_name, train_dataset, test_datasets, raw_test_dfs, output_base_dir):
    print(f"\n--- Fine-tuning model: {model_name} ---")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)

    tokenized_train = tokenize_dataset(train_dataset, tokenizer)

    training_args = TrainingArguments(
        output_dir=f"{output_base_dir}/model",
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        num_train_epochs=3,
        weight_decay=0.01,
        load_best_model_at_end=False,
        logging_dir=f"{output_base_dir}/logs",
        logging_steps=50,
        save_total_limit=2,
        seed=42,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        compute_metrics=compute_metrics,
    )

    # Treniraj model
    trainer.train()

    # Spremi model nakon treninga
    trainer.save_model()

    # Evaluiraj i predvidi na svakom test skupu
    for i, (test_dataset, raw_test_df) in enumerate(zip(test_datasets, raw_test_dfs), start=1):
        print(f"\nEvaluacija na test skupu test-{i}")

        tokenized_test = tokenize_dataset(test_dataset, tokenizer)
        eval_results = trainer.evaluate(eval_dataset=tokenized_test)
        print(f"Evaluacija: {eval_results}")

        predictions_output = trainer.predict(tokenized_test)
        preds = torch.argmax(torch.tensor(predictions_output.predictions), axis=1).numpy()
        labels = predictions_output.label_ids

        print("Confusion Matrix:")
        print(confusion_matrix(labels, preds))

        print("\nClassification Report:")
        print(classification_report(labels, preds, target_names=['negative', 'neutral', 'positive']))

        # Spremi predikcije u CSV
        output_df = raw_test_df.copy()
        output_df['predicted_label'] = preds
        output_df['correct'] = output_df['label'] == output_df['predicted_label']
        output_csv = f"{output_base_dir}/predictions_test_{i}.csv"
        output_df.to_csv(output_csv, index=False)
        print(f"Predikcije spremljene u {output_csv}")

if __name__ == "__main__":
    # Učitaj trening skupove zasebno
    train_files = {
        "train_combined": "TRAIN.csv",
        "train_2": "train-2.csv"
    }

    # Učitaj test skupove
    test_files = ["test-1.csv", "test-2.csv", "test-3.csv"]
    test_datasets = []
    raw_test_dfs = []
    for f in test_files:
        ds, df = load_and_prepare_test_data(f)
        test_datasets.append(ds)
        raw_test_dfs.append(df)

    model_name = "classla/bcms-bertic"

    # Za svaki trening skup treniraj i evaluiraj model na sva tri testa
    for train_name, train_path in train_files.items():
        print(f"\n\n=== Treniranje i evaluacija za trening skup: {train_name} ===")
        train_dataset = load_and_prepare_data(train_path)
        output_dir = f"results_{train_name}"
        train_and_evaluate(model_name, train_dataset, test_datasets, raw_test_dfs, output_dir)




=== Treniranje i evaluacija za trening skup: train_combined ===

--- Fine-tuning model: classla/bcms-bertic ---


Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at classla/bcms-bertic and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Map:   0%|          | 0/7577 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)



Evaluacija na test skupu test-1


Map:   0%|          | 0/653 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Evaluacija: {'eval_loss': 0.8313503265380859, 'eval_accuracy': 0.7136294027565084, 'eval_f1_macro': 0.624180014657386, 'eval_runtime': 16.74, 'eval_samples_per_second': 39.008, 'eval_steps_per_second': 1.254, 'epoch': 3.0}


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Confusion Matrix:
[[109  48   8]
 [ 70 328  32]
 [  4  25  29]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.60      0.66      0.63       165
     neutral       0.82      0.76      0.79       430
    positive       0.42      0.50      0.46        58

    accuracy                           0.71       653
   macro avg       0.61      0.64      0.62       653
weighted avg       0.73      0.71      0.72       653

Predikcije spremljene u results_train_combined/predictions_test_1.csv

Evaluacija na test skupu test-2


Map:   0%|          | 0/741 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Evaluacija: {'eval_loss': 0.23835134506225586, 'eval_accuracy': 0.9257759784075573, 'eval_f1_macro': 0.907760132195386, 'eval_runtime': 19.6933, 'eval_samples_per_second': 37.627, 'eval_steps_per_second': 1.219, 'epoch': 3.0}


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Confusion Matrix:
[[197  16   3]
 [ 14 410   7]
 [  3  12  79]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.92      0.91      0.92       216
     neutral       0.94      0.95      0.94       431
    positive       0.89      0.84      0.86        94

    accuracy                           0.93       741
   macro avg       0.91      0.90      0.91       741
weighted avg       0.93      0.93      0.93       741

Predikcije spremljene u results_train_combined/predictions_test_2.csv

Evaluacija na test skupu test-3


Map:   0%|          | 0/793 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Evaluacija: {'eval_loss': 0.8141497373580933, 'eval_accuracy': 0.7679697351828499, 'eval_f1_macro': 0.7678761268324849, 'eval_runtime': 20.857, 'eval_samples_per_second': 38.021, 'eval_steps_per_second': 1.199, 'epoch': 3.0}


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Confusion Matrix:
[[212  51   4]
 [  7 250   6]
 [  6 110 147]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.94      0.79      0.86       267
     neutral       0.61      0.95      0.74       263
    positive       0.94      0.56      0.70       263

    accuracy                           0.77       793
   macro avg       0.83      0.77      0.77       793
weighted avg       0.83      0.77      0.77       793

Predikcije spremljene u results_train_combined/predictions_test_3.csv


=== Treniranje i evaluacija za trening skup: train_2 ===

--- Fine-tuning model: classla/bcms-bertic ---


Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at classla/bcms-bertic and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Map:   0%|          | 0/2221 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)



Evaluacija na test skupu test-1


Map:   0%|          | 0/653 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Evaluacija: {'eval_loss': 0.8404552340507507, 'eval_accuracy': 0.6906584992343032, 'eval_f1_macro': 0.5999228826553304, 'eval_runtime': 15.1161, 'eval_samples_per_second': 43.199, 'eval_steps_per_second': 1.389, 'epoch': 3.0}


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Confusion Matrix:
[[116  42   7]
 [ 86 309  35]
 [  7  25  26]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.56      0.70      0.62       165
     neutral       0.82      0.72      0.77       430
    positive       0.38      0.45      0.41        58

    accuracy                           0.69       653
   macro avg       0.59      0.62      0.60       653
weighted avg       0.72      0.69      0.70       653

Predikcije spremljene u results_train_2/predictions_test_1.csv

Evaluacija na test skupu test-2


Map:   0%|          | 0/741 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Evaluacija: {'eval_loss': 0.5182289481163025, 'eval_accuracy': 0.8083670715249662, 'eval_f1_macro': 0.7534545808339037, 'eval_runtime': 17.475, 'eval_samples_per_second': 42.403, 'eval_steps_per_second': 1.373, 'epoch': 3.0}


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Confusion Matrix:
[[163  44   9]
 [ 32 381  18]
 [ 10  29  55]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.80      0.75      0.77       216
     neutral       0.84      0.88      0.86       431
    positive       0.67      0.59      0.62        94

    accuracy                           0.81       741
   macro avg       0.77      0.74      0.75       741
weighted avg       0.80      0.81      0.81       741

Predikcije spremljene u results_train_2/predictions_test_2.csv

Evaluacija na test skupu test-3


Map:   0%|          | 0/793 [00:00<?, ? examples/s]

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Evaluacija: {'eval_loss': 0.9036539793014526, 'eval_accuracy': 0.7112232030264817, 'eval_f1_macro': 0.7055643128874013, 'eval_runtime': 18.7008, 'eval_samples_per_second': 42.405, 'eval_steps_per_second': 1.337, 'epoch': 3.0}


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)


Confusion Matrix:
[[204  53  10]
 [ 17 239   7]
 [ 13 129 121]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.87      0.76      0.81       267
     neutral       0.57      0.91      0.70       263
    positive       0.88      0.46      0.60       263

    accuracy                           0.71       793
   macro avg       0.77      0.71      0.71       793
weighted avg       0.77      0.71      0.71       793

Predikcije spremljene u results_train_2/predictions_test_3.csv
